
export const FETCH_STAGES = 'FETCH_STAGES'
export const FETCH_STAGES_REJECTED = 'FETCH_STAGES_REJECTED'
export const FETCH_STAGES_FULFILLED = 'FETCH_STAGES_FULFILLED'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'